// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComzgSu5HO0pkGRw1rRHZqmzvGLQYf_gI',
    appId: '1:93836441459:web:34deaf17af054da641f706',
    messagingSenderId: '93836441459',
    projectId: 'fruit-app-4f153',
    authDomain: 'fruit-app-4f153.firebaseapp.com',
    storageBucket: 'fruit-app-4f153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZnWfimQxqZIa1bWbOT0cYd8CajxqoD0A',
    appId: '1:93836441459:android:3f928e1133dcba6741f706',
    messagingSenderId: '93836441459',
    projectId: 'fruit-app-4f153',
    storageBucket: 'fruit-app-4f153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL1nIKHa9LswXg7cOoPX2TZLaEIQkPkQQ',
    appId: '1:93836441459:ios:eb3cbc71c0424d7941f706',
    messagingSenderId: '93836441459',
    projectId: 'fruit-app-4f153',
    storageBucket: 'fruit-app-4f153.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL1nIKHa9LswXg7cOoPX2TZLaEIQkPkQQ',
    appId: '1:93836441459:ios:eb3cbc71c0424d7941f706',
    messagingSenderId: '93836441459',
    projectId: 'fruit-app-4f153',
    storageBucket: 'fruit-app-4f153.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComzgSu5HO0pkGRw1rRHZqmzvGLQYf_gI',
    appId: '1:93836441459:web:0dcdb4b3ce219bc941f706',
    messagingSenderId: '93836441459',
    projectId: 'fruit-app-4f153',
    authDomain: 'fruit-app-4f153.firebaseapp.com',
    storageBucket: 'fruit-app-4f153.firebasestorage.app',
  );
}
